* itty - The very small erlang webserver
** Hello
Itty was written as a way for me to learn erlang.  It's aim is to eventually me a complete, but very lean webserver.  The focus is not necessarily on speed, performance or security, but on a clear design that is easy to read through and understand.

** Eventually
I would like to include tutorials to take the reader through the step by step process of building up the webserver from its embryonic single process, to multiple processes working together to create a functioning webserver

** For Now
Thanks for checking this out.  Feel free to send your comments to zach@thehelpfulhacker.net

** Todo
- [ ] document (edoc see mochiweb for examples, makefile)
- [ ] do something better with the template 404 and 500 pages
- [ ] the actual codes for 404/500 appear to be passed around too much, look into this
- [ ] actually use status 500 for something
- [ ] break out into separate modules
- [ ] need ot clean up the relationship between "handler" and "serve_request"
- [ ] yep probably need a content type lol
** Done
- [X] config file
      See - http://spawnlink.com/articles/managing-application-configuration/
- [X] logging
- [X] needs to try "index.html, index.html, etc"
- [X] use records for datatypes
- [X] Use error codes
- [X] log in actual CLF - ehhh i implemented CEF (Close Enough Format)
      
